export const setNotificationHandler = jest.fn();
export const getPermissionsAsync = jest.fn(() => Promise.resolve({ status: 'granted' }));
export const requestPermissionsAsync = jest.fn(() => Promise.resolve({ status: 'granted' }));
export const scheduleNotificationAsync = jest.fn(() => Promise.resolve('notification-id'));
export const cancelScheduledNotificationAsync = jest.fn();
export const cancelAllScheduledNotificationsAsync = jest.fn();
export const getAllScheduledNotificationsAsync = jest.fn(() => Promise.resolve([]));
export const setNotificationCategoryAsync = jest.fn(() => Promise.resolve(null));
export const dismissNotificationAsync = jest.fn(() => Promise.resolve());
export const addNotificationResponseReceivedListener = jest.fn(() => ({ remove: jest.fn() }));
export const DEFAULT_ACTION_IDENTIFIER = 'expo.modules.notifications.actions.DEFAULT';
